# Where to go next



## MASH support

There are lots of ways to learn R, and you do not have to learn it alone. Here at MASH, we offer friendly and specialist support from workshops to 1:1 sessions to suit your needs. Here are the main ways we can support you.

### MASH workshops

MASH runs workshops covering statistics, mathematics and software skills.

R workshops are a great way to learn alongside other students and ask questions as you go.

We offer [R workshops for ultra-beginners](https://301skills.shef.ac.uk/events/284/upcoming). These are designed for people who want to learn R from the very basics, without any prior knowledge - excellent if you have never coded before.

We also have more bespoke R workshops such as 

- [MASH workshop: Using R for data visualisation](https://301skills.shef.ac.uk/events/287/upcoming) 
- [MASH workshop: Using R for hypothesis testing](https://301skills.shef.ac.uk/events/391/upcoming)
- [MASH workshop: Using R for regression](https://301skills.shef.ac.uk/events/291/upcoming)

You can find and book workshops on the [MASH workshops booking calendar](https://students.sheffield.ac.uk/mash/workshops#bookig-calendar)

### MASH online resources

The [MASH First steps in R resources](https://sheffield.ac.uk/mash/stats-resources/r#First-steps) are designed to help you get started from the beginning, providing videos and help pages for getting started with R.

### MASH 1-1 support

You can also book a 1-1 appointment with MASH.

A 1:1 can be particularly useful if you have a specific question about:

-   A research problem
-   How to implement a statistical method
-   R code that is not working
-   Interpreting your output

You can book a 1-1 appointment on the [MASH statistics 1-1 appointment booking page](https://students.sheffield.ac.uk/mash/bookings/stats-support#book-here)


## Where to go next

Once you have mastered the basics, there are lots of other resources you can use to continue learning.

### YaRrr! The Pirate's Guide to R

[YaRrr! The Pirate's Guide to R](https://bookdown.org/ndphillips/YaRrr/) is a clear, free online textbook.

It provides an accessible introduction to R and includes examples that you can work through yourself.

### R for Data Science
[R for Data Science](https://www.google.co.uk/books/edition/R_for_Data_Science/I6y3DQAAQBAJ?hl=en&gbpv=0) by Hadley Wickham is a great guide for importing, wrangling, manipulating and visualising data. 


### Learn R by example

[Learn R by example](https://www.learnbyexample.org/r/) is an easily to follow website organised around examples.

It covers topics ranging from basic R syntax through data structures, functions, data import, graphics and more.



BELOW IS OLD MASH CONTENT 
## Introduction 

There are many free resources for getting to grips with ***R*** and the ***RStudio*** software. Because ***R*** is a programming language, there are often different ways to achieve the same aims. Which method you prefer is up to you. For this reason we would recommend that a learner uses a variety of resources. Fortunately, there are many free resources available to get you going.

## First Steps in ***R*** from MASH

Although there are many excellent introductory ***R*** resources, most start by assuming the learner has downloaded ***R*** and/or ***RStudio*** and is aware of some of the ideas behind coding (e.g. the difference between a console and a GUI).

If you are completely new to coding or you would like to know what software to download in order to get going, our "First Steps in ***R***" resources are for you. There are video tutorials and written help sheets which start at the very beginning and get you up and running.

You can find the resources at <a href="https://www.sheffield.ac.uk/mash/statistics/r" target="_blank" title="Go to MASH">MASH</a>.

These resources are made to suit the needs of members of the University of Sheffield. If there are resources you would like but which are not currently available through MASH, please let us know here: <a href="https://docs.google.com/forms/d/e/1FAIpQLSdza6rosmBlQtWCrjvxPhTCO64AAmBrS3hZT2MYXBfAQm1qdA/viewform" target="_blank" title="Go to contact MASH">contact MASH</a>.

## ***R*** Workshops or MASH 1:1 Sessions

MASH run workshops in ***R***. Details can be found on <a href="https://www.sheffield.ac.uk/mash/workshops" target="_blank" title="Go to MASH workshops">MASH workshops</a>.

We also have bookable one-to-one appointments and drop in sessions. If you would like help getting going you can find more details at <a href="https://www.sheffield.ac.uk/mash/bookings" target="_blank" title="Go to MASH bookings">MASH bookings</a>.

## Websites/Online Textbooks

An introductory ***R*** course is available on this website: <a href="https://www.datacamp.com/courses/free-introduction-to-r" target="_blank" title="Go to datacamp">datacamp</a>.

<a href="https://bookdown.org/ndphillips/YaRrr" target="_blank" title="Go to YaRrr! The Pirate's Guide to R">YaRrr! The Pirate's Guide to R</a> is a clear, free online textbook.

<a href="https://www.learnbyexample.org/r" target="_blank" title="Go to Learn by example">Learn by example</a> is an easily followable and well set out website with a good guide to ***R***.

<a href="https://www.r-tutor.com" target="_blank" title="Go to R Tutor">R Tutor</a> does what it says on the tin!

## Swirl

"Swirl" is a package for learning ***R*** interactively within ***RStudio***.

Begin by installing the <code style="color: blue;">swirl</code> package by typing the following command into the console:

<center>
    <code style="color: blue;">install.packages("swirl")</code>
</center>

Once the installation is complete, launch the <code style="color: blue;">swirl</code> package by typing

<center>
    <code style="color: blue;">library("swirl")</code>
</center>

From here <code style="color: blue;">swirl</code> will automatically begin interacting with you. Simply read the instructions on the screen and enter your responses.
