# Support

## MASH support

There are lots of ways to learn R, and you do not have to learn it alone. Here at MASH, we offer friendly and specialist support from workshops to 1:1 sessions to suit your needs. Here are the main ways we can support you.

### MASH workshops

MASH runs workshops covering statistics, mathematics and software skills.

R workshops are a great way to learn alongside other students and ask questions as you go.

We offer [R workshops for ultra-beginners](https://301skills.shef.ac.uk/events/284/upcoming). These are designed for people who want to learn R from the very basics, without any prior knowledge - excellent if you have never coded before.

We also have more bespoke R workshops such as 

- [MASH workshop: Using R for data visualisation](https://301skills.shef.ac.uk/events/287/upcoming) 
- [MASH workshop: Using R for hypothesis testing](https://301skills.shef.ac.uk/events/391/upcoming)
- [MASH workshop: Using R for regression](https://301skills.shef.ac.uk/events/291/upcoming)

You can find and book workshops on the [MASH workshops booking calendar](https://students.sheffield.ac.uk/mash/workshops#bookig-calendar)

### MASH online resources

The [MASH First steps in R resources](https://sheffield.ac.uk/mash/stats-resources/r#First-steps) are designed to help you get started from the beginning, providing videos and help pages for getting started with R.

### MASH 1-1 support

You can also book a 1-1 appointment with MASH.

A 1:1 can be particularly useful if you have a specific question about:

-   A research problem
-   How to implement a statistical method
-   R code that is not working
-   Interpreting your output

You can book a 1-1 appointment on the [MASH statistics 1-1 appointment booking page](https://students.sheffield.ac.uk/mash/bookings/stats-support#book-here)

